eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
   port: 8761

spring:
  application:
    name: eureka-local
#  boot:
#    admin:
#      client:
#        url: http://127.0.0.1:99
#        instance:
#          service-url: http://${eureka.instance.instance-id}
